/**
 * Claude model definitions for Vertex AI
 * Source: https://cloud.google.com/vertex-ai/generative-ai/docs/partner-models/use-partner-models
 * Pricing: https://cloud.google.com/vertex-ai/generative-ai/pricing#partner-models
 * All prices per 1M tokens (<=200K input tokens)
 * `cost` = global endpoint; `costRegional` = non-global (us-east5, europe-west1,
 * asia-southeast1, us/eu multi-region) — uniformly 10% above global.
 * Cache write prices are for 5-minute TTL
 */

import type { VertexModelConfig } from "../types.js";

export const CLAUDE_MODELS: VertexModelConfig[] = [
  // Claude 5 series
  {
    id: "claude-sonnet-5",
    name: "Claude Sonnet 5",
    apiId: "claude-sonnet-5",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 1000000,
    maxTokens: 128000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 2.0,
      output: 10.0,
      cacheRead: 0.2,
      cacheWrite: 2.5,
    },
    costRegional: {
      input: 2.2,
      output: 11.0,
      cacheRead: 0.22,
      cacheWrite: 2.75,
    },
    region: "global",
  },
  // Claude 4.8 series
  {
    id: "claude-opus-4-8",
    name: "Claude Opus 4.8",
    apiId: "claude-opus-4-8",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 1000000,
    maxTokens: 128000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 5.0,
      output: 25.0,
      cacheRead: 0.5,
      cacheWrite: 6.25,
    },
    costRegional: {
      input: 5.5,
      output: 27.5,
      cacheRead: 0.55,
      cacheWrite: 6.875,
    },
    region: "global",
  },

  // Claude 4.7 series
  {
    id: "claude-opus-4-7",
    name: "Claude Opus 4.7",
    apiId: "claude-opus-4-7",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 1000000,
    maxTokens: 128000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 5.0,
      output: 25.0,
      cacheRead: 0.5,
      cacheWrite: 6.25,
    },
    costRegional: {
      input: 5.5,
      output: 27.5,
      cacheRead: 0.55,
      cacheWrite: 6.875,
    },
    region: "global",
  },

  // Claude 4.6 series
  {
    id: "claude-opus-4-6",
    name: "Claude Opus 4.6",
    apiId: "claude-opus-4-6",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 1000000,
    maxTokens: 128000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 5.0,
      output: 25.0,
      cacheRead: 0.5,
      cacheWrite: 6.25,
    },
    costRegional: {
      input: 5.5,
      output: 27.5,
      cacheRead: 0.55,
      cacheWrite: 6.875,
    },
    region: "global",
  },
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    apiId: "claude-sonnet-4-6",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 1000000,
    maxTokens: 128000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 3.0,
      output: 15.0,
      cacheRead: 0.3,
      cacheWrite: 3.75,
    },
    costRegional: {
      input: 3.3,
      output: 16.5,
      cacheRead: 0.33,
      cacheWrite: 4.125,
    },
    region: "global",
  },

  // Claude 4.5 series
  {
    id: "claude-opus-4-5",
    name: "Claude Opus 4.5",
    apiId: "claude-opus-4-5@20251101",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 200000,
    maxTokens: 32000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 5.0,
      output: 25.0,
      cacheRead: 0.5,
      cacheWrite: 6.25,
    },
    costRegional: {
      input: 5.5,
      output: 27.5,
      cacheRead: 0.55,
      cacheWrite: 6.875,
    },
    region: "global",
  },
  {
    id: "claude-sonnet-4-5",
    name: "Claude Sonnet 4.5",
    apiId: "claude-sonnet-4-5@20250929",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 200000,
    maxTokens: 64000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 3.0,
      output: 15.0,
      cacheRead: 0.3,
      cacheWrite: 3.75,
    },
    costRegional: {
      input: 3.3,
      output: 16.5,
      cacheRead: 0.33,
      cacheWrite: 4.125,
    },
    region: "global",
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    apiId: "claude-haiku-4-5@20251001",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 200000,
    maxTokens: 64000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 1.0,
      output: 5.0,
      cacheRead: 0.1,
      cacheWrite: 1.25,
    },
    costRegional: {
      input: 1.1,
      output: 5.5,
      cacheRead: 0.11,
      cacheWrite: 1.375,
    },
    region: "global",
  },

  // Claude 4.1 series
  {
    id: "claude-opus-4-1",
    name: "Claude Opus 4.1",
    apiId: "claude-opus-4-1@20250805",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 200000,
    maxTokens: 32000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 15.0,
      output: 75.0,
      cacheRead: 1.5,
      cacheWrite: 18.75,
    },
    region: "global",
  },

  // Claude 4.0 series
  {
    id: "claude-opus-4",
    name: "Claude Opus 4",
    apiId: "claude-opus-4@20250514",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 200000,
    maxTokens: 32000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 15.0,
      output: 75.0,
      cacheRead: 1.5,
      cacheWrite: 18.75,
    },
    region: "global",
  },
  {
    id: "claude-sonnet-4",
    name: "Claude Sonnet 4",
    apiId: "claude-sonnet-4@20250514",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 200000,
    maxTokens: 64000,
    input: ["text", "image"],
    reasoning: true,
    tools: true,
    cost: {
      input: 3.0,
      output: 15.0,
      cacheRead: 0.3,
      cacheWrite: 3.75,
    },
    region: "global",
  },

  // Claude 3.5 series
  {
    id: "claude-3-5-sonnet-v2",
    name: "Claude 3.5 Sonnet v2",
    apiId: "claude-3-5-sonnet-v2@20241022",
    publisher: "anthropic",
    endpointType: "maas",
    contextWindow: 200000,
    maxTokens: 8192,
    input: ["text", "image"],
    reasoning: false,
    tools: true,
    cost: {
      input: 3.0,
      output: 15.0,
      cacheRead: 0.3,
      cacheWrite: 3.75,
    },
    region: "global",
  },
];
